
SET(ANDROID_TOOLS_HOME $ENV{ANDROID_TOOLS_HOME})

SET(CMAKE_SYSROOT ${ANDROID_TOOLS_HOME}/sysroot)
#SET(CMAKE_SYSROOT_COMPILE ${ANDROID_TOOLS_HOME}/sysroot)
SET(CMAKE_SYSROOT_LINK ${ANDROID_TOOLS_HOME}/sysroot)

SET(CMAKE_FIND_ROOT_PATH ${ANDROID_TOOLS_HOME}/sysroot)
SET(TOOLCHAIN "$ENV{TOOLCHAIN}")
if("${TOOLCHAIN}" MATCHES ".*clang.*")
    SET(CMAKE_CXX_COMPILER ${ANDROID_TOOLS_HOME}/bin/clang++)
    SET(CMAKE_C_COMPILER ${ANDROID_TOOLS_HOME}/bin/clang)
else()
    SET(CMAKE_CXX_COMPILER ${ANDROID_TOOLS_HOME}/bin/arm-linux-androideabi-g++)
    SET(CMAKE_C_COMPILER ${ANDROID_TOOLS_HOME}/bin/arm-linux-androideabi-gcc)
endif()

SET(CMAKE_CXX_COMPILER_LAUNCHER ccache)
SET(CMAKE_C_COMPILER_LAUNCHER ccache)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
