
SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
SET(CMAKE_RANLIB      x86_64-w64-mingw32-ranlib)
SET(CMAKE_INSTALL_PREFIX /usr/x86_64-w64-mingw32)

SET(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/wine64)

SET(CMAKE_CXX_COMPILER_LAUNCHER ccache)
SET(CMAKE_C_COMPILER_LAUNCHER ccache)

SET(CMAKE_FIND_ROOT_PATH  /usr/x86_64-w64-mingw32/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
