
SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
SET(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
SET(CMAKE_RC_COMPILER i686-w64-mingw32-windres)

SET(CMAKE_CXX_COMPILER_LAUNCHER ccache)
SET(CMAKE_C_COMPILER_LAUNCHER ccache)

SET(CMAKE_FIND_ROOT_PATH  /usr/i686-w64-mingw32/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
