# - Try to find the SOSI library
#
# Once done this will define
#
#  SOSI_FOUND - System has libgta
#  SOSI_INCLUDE_DIR - The libgta include directory
#  SOSI_LIBRARIES - The libraries needed to use libgta

FIND_PATH(SOSI_INCLUDE_DIR
          NAMES fyba.h
          PATH_SUFFIXES fyba)
FIND_LIBRARY(SOSI_FYBA_LIBRARY NAMES fyba)
FIND_LIBRARY(SOSI_FYGM_LIBRARY NAMES fygm)
FIND_LIBRARY(SOSI_FYUT_LIBRARY NAMES fyut)
SET(SOSI_LIBRARIES ${SOSI_FYBA_LIBRARY} ${SOSI_FYGM_LIBRARY} ${SOSI_FYUT_LIBRARY} CACHE PATH "")
MARK_AS_ADVANCED(SOSI_INCLUDE_DIR SOSI_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SOSI
    REQUIRED_VARS SOSI_LIBRARIES SOSI_INCLUDE_DIR
)
